databases:
  - name: TechStream
    databaseName: TechStream_production
    user: TechStream

services:
  - type: web
    name: TechStream
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: TechStream
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false